// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Dog struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	IsGoodBoi bool   `json:"isGoodBoi"`
}

type NewDog struct {
	Name      string `json:"name"`
	IsGoodBoi bool   `json:"isGoodBoi"`
}

type DogID struct {
	ID string `json:"id"`
}
